// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/yang201396/GoExamples/mission"
	"github.com/yang201396/GoExamples/monster"
	"github.com/yang201396/GoExamples/player"
)

// Injectors from wire.go:

func InitMission(MonsterName monster.MonsterParam, PlayerNamp player.PlayerParam) mission.Mission {
	playerPlayer := player.NewPlayer(PlayerNamp)
	monsterMonster := monster.NewMonster(MonsterName)
	missionMission := mission.NewMission(playerPlayer, monsterMonster)
	return missionMission
}
